-- MySQL Script generated by MySQL Workbench
-- Fri Sep  6 08:07:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lucianoamaral_goepa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lucianoamaral_goepa` ;

-- -----------------------------------------------------
-- Schema lucianoamaral_goepa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lucianoamaral_goepa` DEFAULT CHARACTER SET utf8 ;
USE `lucianoamaral_goepa` ;

-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`enderecos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`enderecos` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(250) NULL,
  `numero` VARCHAR(45) NULL,
  `cidade` VARCHAR(150) NULL,
  `uf` VARCHAR(45) NULL,
  `bairro` VARCHAR(150) NULL,
  `cep` VARCHAR(15) NULL,
  `complemento` VARCHAR(250) NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`empresas` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`empresas` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `fk_endereco` INT NULL,
  `razao_social` VARCHAR(250) NULL,
  `nome_fantasia` VARCHAR(250) NULL,
  `status` INT NULL,
  `fone_1` VARCHAR(45) NULL,
  `fone_2` VARCHAR(45) NULL,
  `email` VARCHAR(150) NULL,
  `site` VARCHAR(150) NULL,
  `cnpj` VARCHAR(45) NULL,
  `data_cadastro` DATE NULL,
  `codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_empresa`),
  INDEX `fk_endereco_empresa_idx` (`fk_endereco` ASC),
  CONSTRAINT `fk_endereco_empresa`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `lucianoamaral_goepa`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `senha` VARCHAR(150) NULL,
  `status` INT NULL,
  `nome_completo` VARCHAR(250) NULL,
  `cpf` VARCHAR(50) NULL,
  `tel` VARCHAR(50) NULL,
  `email` VARCHAR(250) NULL,
  `data_cadastro` DATE NULL,
  `token` VARCHAR(250) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`modulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`modulos` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`modulos` (
  `id_modulo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NULL,
  `codigo` VARCHAR(150) NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`usuarios_modulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`usuarios_modulos` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`usuarios_modulos` (
  `id_usuario_modulo` INT NOT NULL AUTO_INCREMENT,
  `fk_usuario` INT NULL,
  `fk_modulo` INT NULL,
  PRIMARY KEY (`id_usuario_modulo`),
  INDEX `id_operador_modulo_idx` (`fk_usuario` ASC),
  INDEX `id_modulo_operador_idx` (`fk_modulo` ASC),
  CONSTRAINT `fk_usuario_modulo`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `lucianoamaral_goepa`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modulo_usuario`
    FOREIGN KEY (`fk_modulo`)
    REFERENCES `lucianoamaral_goepa`.`modulos` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`entidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`entidades` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`entidades` (
  `id_entidade` INT NOT NULL AUTO_INCREMENT,
  `fk_relacao` INT NULL,
  `nome` VARCHAR(150) NULL,
  `codigo` VARCHAR(45) NULL,
  `tipo` INT NULL,
  `status` INT NULL,
  `params` VARCHAR(250) NULL,
  PRIMARY KEY (`id_entidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`empresas_modulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`empresas_modulos` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`empresas_modulos` (
  `id_empresa_modulo` INT NOT NULL AUTO_INCREMENT,
  `fk_empresa` INT NULL,
  `fk_modulo` INT NULL,
  PRIMARY KEY (`id_empresa_modulo`),
  INDEX `id_modulo_operador_idx` (`fk_modulo` ASC),
  INDEX `id_empresa_modulo_idx` (`fk_empresa` ASC),
  CONSTRAINT `fk_empresa_modulo`
    FOREIGN KEY (`fk_empresa`)
    REFERENCES `lucianoamaral_goepa`.`empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modulo_empresa`
    FOREIGN KEY (`fk_modulo`)
    REFERENCES `lucianoamaral_goepa`.`modulos` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`grupos_de_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`grupos_de_usuarios` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`grupos_de_usuarios` (
  `id_grupo_de_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NULL,
  `codigo` VARCHAR(45) NULL,
  `descricao` VARCHAR(150) NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_grupo_de_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`usuarios_grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`usuarios_grupos` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`usuarios_grupos` (
  `id_usuario_grupo` INT NOT NULL AUTO_INCREMENT,
  `fk_usuario` INT NULL,
  `fk_grupo` INT NULL,
  PRIMARY KEY (`id_usuario_grupo`),
  INDEX `fk_usuario_grupo_idx` (`fk_usuario` ASC),
  INDEX `fk_grupo_usuario_idx` (`fk_grupo` ASC),
  CONSTRAINT `fk_usuario_grupo`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `lucianoamaral_goepa`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_usuario`
    FOREIGN KEY (`fk_grupo`)
    REFERENCES `lucianoamaral_goepa`.`grupos_de_usuarios` (`id_grupo_de_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`acessos` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`acessos` (
  `id_acesso` INT NOT NULL AUTO_INCREMENT,
  `fk_modulo` INT NULL,
  `nome` VARCHAR(150) NULL,
  `tipo` INT NULL COMMENT '1 = ver_edt_exc, 2 = sim_nao',
  `codigo` VARCHAR(45) CHARACTER SET 'big5' NULL,
  `ordem` INT NULL,
  PRIMARY KEY (`id_acesso`),
  INDEX `fk_modulo_idx` (`fk_modulo` ASC),
  CONSTRAINT `fk_modulo`
    FOREIGN KEY (`fk_modulo`)
    REFERENCES `lucianoamaral_goepa`.`modulos` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`grupos_acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`grupos_acessos` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`grupos_acessos` (
  `id_grupo_acesso` INT NOT NULL AUTO_INCREMENT,
  `fk_grupo` INT NULL,
  `fk_acesso` INT NULL,
  `valor` INT NULL COMMENT '1 = ver, 2 = edt, 3 = exc, 4 = sim, 5 = nao',
  PRIMARY KEY (`id_grupo_acesso`),
  INDEX `fk_grupo_acesso_idx` (`fk_grupo` ASC),
  INDEX `fk_acesso_grupo_idx` (`fk_acesso` ASC),
  CONSTRAINT `fk_grupo_acesso`
    FOREIGN KEY (`fk_grupo`)
    REFERENCES `lucianoamaral_goepa`.`grupos_de_usuarios` (`id_grupo_de_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acesso_grupo`
    FOREIGN KEY (`fk_acesso`)
    REFERENCES `lucianoamaral_goepa`.`acessos` (`id_acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`modulos_permitidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`modulos_permitidos` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`modulos_permitidos` (
  `id_modulo_permitido` INT NOT NULL AUTO_INCREMENT,
  `fk_modulo` INT NULL,
  `fk_empresa` INT NULL,
  PRIMARY KEY (`id_modulo_permitido`),
  INDEX `fk_modulo_mod_permitido_idx` (`fk_modulo` ASC),
  INDEX `fk_empresa_mod_permitido_idx` (`fk_empresa` ASC),
  CONSTRAINT `fk_modulo_mod_permitido`
    FOREIGN KEY (`fk_modulo`)
    REFERENCES `lucianoamaral_goepa`.`modulos` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_mod_permitido`
    FOREIGN KEY (`fk_empresa`)
    REFERENCES `lucianoamaral_goepa`.`empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`logs` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`logs` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `fk_usuario` INT NULL,
  `fk_alvo` INT NULL,
  `tipo` INT NULL,
  `data` DATE NULL,
  `hora` INT NULL,
  `min` INT NULL,
  `acao` INT NULL,
  PRIMARY KEY (`id_log`),
  INDEX `fk_usuario_log_idx` (`fk_usuario` ASC),
  CONSTRAINT `fk_usuario_log`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `lucianoamaral_goepa`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`item_documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`item_documentos` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`item_documentos` (
  `id_item_documento` INT NOT NULL AUTO_INCREMENT,
  `fk_documento` INT NULL,
  `fk_criador` INT NULL,
  `fk_revisor` INT NULL,
  `fk_autorizador` INT NULL,
  `descricao_versao` VARCHAR(150) NULL,
  `cod_versao` VARCHAR(45) NULL,
  `nome_arq` VARCHAR(150) NULL,
  `data_criacao` DATE NULL,
  `data_revisao` DATE NULL,
  `data_autorizacao` DATE NULL,
  `tipo` INT NULL,
  `extensao` VARCHAR(45) NULL,
  `tamanho` INT NULL COMMENT 'em bytes',
  `status` INT NULL COMMENT '0 versao obsoluta, 1 versao atual',
  `situacao` INT NULL COMMENT '0 criado nao revisado nao autorizado, 1 criado e revisado nao autorizado, 2 criado revisado e autorizado',
  PRIMARY KEY (`id_item_documento`),
  INDEX `fk_criador_item_doc_idx` (`fk_criador` ASC),
  INDEX `fk_revisor_item_doc_idx` (`fk_revisor` ASC),
  INDEX `fk_autorizador_item_doc_idx` (`fk_autorizador` ASC),
  CONSTRAINT `fk_criador_item_doc`
    FOREIGN KEY (`fk_criador`)
    REFERENCES `lucianoamaral_goepa`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_revisor_item_doc`
    FOREIGN KEY (`fk_revisor`)
    REFERENCES `lucianoamaral_goepa`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autorizador_item_doc`
    FOREIGN KEY (`fk_autorizador`)
    REFERENCES `lucianoamaral_goepa`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`membros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`membros` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`membros` (
  `id_membro` INT NOT NULL AUTO_INCREMENT,
  `fk_endereco` INT NULL,
  `fk_usuario` INT NULL,
  `fk_loja` INT NULL,
  `fk_trabalho_endereco` INT NULL,
  `nome` VARCHAR(250) NULL,
  `nascimento` DATE NULL,
  `uf` VARCHAR(10) NULL,
  `nacionalidade` VARCHAR(250) NULL,
  `estado_civil` INT NULL,
  `data_casamento` DATE NULL,
  `tipo_sangue` VARCHAR(45) NULL,
  `profissao` VARCHAR(250) NULL,
  `aposentado` INT NULL,
  `nome_pai` VARCHAR(250) NULL,
  `nome_mae` VARCHAR(250) NULL,
  `cim` VARCHAR(25) NULL,
  `cpf` VARCHAR(25) NULL,
  `rg` VARCHAR(25) NULL,
  `rg_expeditor` VARCHAR(150) NULL,
  `rg_data_expedicao` DATE NULL,
  `titulo_eleitor` VARCHAR(25) NULL,
  `titulo_eleitor_zona` VARCHAR(25) NULL,
  `titulo_eleitor_sessao` VARCHAR(25) NULL,
  `tel_1` VARCHAR(45) NULL,
  `tel_2` VARCHAR(45) NULL,
  `tel_3` VARCHAR(45) NULL,
  `email` VARCHAR(150) NULL,
  `nome_esposa` VARCHAR(250) NULL,
  `nascimento_esposa` DATE NULL,
  `trabalho_empresa` VARCHAR(250) NULL,
  `data_cadastro` DATE NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_membro`),
  INDEX `fk_endereco_membro_idx` (`fk_endereco` ASC),
  INDEX `fk_usuario_membro_idx` (`fk_usuario` ASC),
  INDEX `fk_loja_membro_idx` (`fk_loja` ASC),
  INDEX `fk_trabalho_endereco_membro_idx` (`fk_trabalho_endereco` ASC),
  CONSTRAINT `fk_endereco_membro`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `lucianoamaral_goepa`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_membro`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `lucianoamaral_goepa`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loja_membro`
    FOREIGN KEY (`fk_loja`)
    REFERENCES `lucianoamaral_goepa`.`empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabalho_endereco_membro`
    FOREIGN KEY (`fk_trabalho_endereco`)
    REFERENCES `lucianoamaral_goepa`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lucianoamaral_goepa`.`filhos_membros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lucianoamaral_goepa`.`filhos_membros` ;

CREATE TABLE IF NOT EXISTS `lucianoamaral_goepa`.`filhos_membros` (
  `id_filho_membro` INT NOT NULL AUTO_INCREMENT,
  `fk_membro` INT NULL,
  `nome` VARCHAR(250) NULL,
  `sexo` INT NULL,
  `nascimento` DATE NULL,
  PRIMARY KEY (`id_filho_membro`),
  INDEX `fk_membro_filho_idx` (`fk_membro` ASC),
  CONSTRAINT `fk_membro_filho`
    FOREIGN KEY (`fk_membro`)
    REFERENCES `lucianoamaral_goepa`.`membros` (`id_membro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
